#!/bin/bash
SRC_ROOT=$(dirname "$0")
OWL_ROOT=$(dirname "$SRC_ROOT")
# Forward OWL_TRACE and other env vars through Pin to the target process
export NOBANNER=1
export LD_PRELOAD=${OWL_ROOT}/build/lib/gpu_trace.so
exec ${OWL_ROOT}/src/owl_monitor/pin_root/pin -t ${OWL_ROOT}/build/lib/cpu_trace.so -- $@